# Generated by Django 4.2.5 on 2023-10-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_version_options_alter_version_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(blank=True, default=1, verbose_name='Номер версии'),
        ),
    ]
